### ISSUE TITLE
Configuration defaults will be used due to OSError

### ISSUE THREAD

**Issue by bm1391** [SpamScope/spamscope#13]
Errors appearing under the spamscope_debug worker.log

> 

> 2018-10-11 08:54:22.519 phishing Thread-42 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:22.520 phishing Thread-44 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:22.520 phishing Thread-43 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:22.520 phishing Thread-37 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:22.522 phishing Thread-41 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:22.525 phishing Thread-38 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:23.509 phishing Thread-39 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))
> 
> 2018-10-11 08:54:23.509 phishing Thread-40 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
>   warn(ConfigurationMissingWarning(msg))

> --
>

**Comment by fedelemantuano** [comment]
Don't worry. This is only a warning of `astropy` library, that I use to parse result from `SpamAssassin` analyzer.

```
OSError
        If the home directory cannot be located - usually means you are running
        Astropy on some obscure platform that doesn't have standard home
        directories.
```

Fail this control:

```
if 'HOME' in os.environ:
```

I will try to avoid this warning.
