### ISSUE TITLE
Serializer Exception & Pipe Broken

### ISSUE THREAD

**Issue by Hopyoprop** [SpamScope/spamscope#19]
Fresh docker image of spamscope and it brings this error.

> org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: /usr/local/lib/python2.7/dist-packages/astropy/config/configuration.py

I have tried using the topology debug and the debug-iter already and both have this error. Upon submitting a mail to be analysed, the mail is analysed, put into /tmp/failed and this error still remains there. No output is received.

Help would be appreciated on this matter.

**Comment by fedelemantuano** [comment]
I will migrate to Python 3.
